version: '3.8'

services:

  web:         
    build: 
      context: .
    command: sh -c "python -m flask run --host=0.0.0.0 --port=8000"
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app 
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=inventory_db
      - DB_USER=root
      - DB_PASS=password

  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=inventory_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin_password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_SSL_CA=''
      - MYSQL_SSL_CERT=''
      - MYSQL_SSL_KEY=''
      - innodb_force_recovery=1
    ports:
      - "3307:3306"

volumes:

  db_data:
    driver: local